export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import './globals.css'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header className="bg-zinc-900 p-10 text-white">
        <h1 className='text-3xl'>Header</h1>
      </header>
      <div className='h-[70vh]'>

        {children}
      </div>
      <footer className="bg-gray-300  p-10">
        <h1 className='text-3xl'>Footer</h1>
      </footer>
        </body>
    </html>
  )
}
